version: '20260214.140535'
debugging_visualization:
  draw_grid: true
  grid_size: 100
output:
  frame_skip: 3
  save_video: true
stopsign_detection:
  in_zone_frame_threshold: 2
  max_movement_speed: 20
  min_stop_time: 2.0
  out_zone_frame_threshold: 2
  parked_frame_threshold: 60
  pre_stop_line:
  - - 2090.9747292418774
    - 847.9135196374623
  - - 2116.389891696751
    - 1065.4361782477342
  stop_zone:
  - - 1310.0361010830325
    - 865.3153323262841
  - - 1383.971119133574
    - 863.1401057401813
  - - 1032.7797833935017
    - 1048.0343655589124
  - - 954.2238267148015
    - 1039.3334592145015
  capture_line:
  - - 1781.3718411552347
    - 837.0373867069487
  - - 1767.509025270758
    - 1061.0857250755287
  stop_speed_threshold: 50
  unparked_frame_threshold: 20
  unparked_speed_threshold: 30
stream_settings:
  fps: 15
  input_source: live
  vehicle_classes:
  - 1
  - 2
  - 3
  - 5
  - 6
  - 7
tracking:
  use_kalman_filter: true
video_processing:
  crop_side: 0
  crop_top: 0
  frame_buffer_size: 500
  scale: 0.75
